#include %A_ScriptDir%\controller\application-vscode.ahk
#include %A_ScriptDir%\controller\application.ahk
#include %A_ScriptDir%\controller\everything.ahk
#include %A_ScriptDir%\controller\global-mouse-cursor.ahk
#include %A_ScriptDir%\controller\global.ahk
#include %A_ScriptDir%\controller\linux-fzf.ahk
#include %A_ScriptDir%\controller\terminal.ahk
#include %A_ScriptDir%\controller\time.ahk
#include %A_ScriptDir%\controller\vscode.ahk
#include %A_ScriptDir%\controller\web.ahk
#include %A_ScriptDir%\controller\windows.ahk
#include %A_ScriptDir%\controller\wps.ahk
#include %A_ScriptDir%\controller\wsl.ahk
#include %A_ScriptDir%\function\activeApplication.ahk
#include %A_ScriptDir%\function\function.ahk
#include %A_ScriptDir%\function\IME.ahk
#include %A_ScriptDir%\function\send.ahk
#include %A_ScriptDir%\myhotkey.ahk
#include %A_ScriptDir%\route\route-ip.ahk
#include %A_ScriptDir%\route\route-openbmc-2600.ahk
#include %A_ScriptDir%\route\route-openbmc-romlus.ahk
#include %A_ScriptDir%\route\route-openbmc.ahk
#include %A_ScriptDir%\route\route-wsl.ahk
#include %A_ScriptDir%\route\route.ahk
#include %A_ScriptDir%\shortcut\output.ahk
#include %A_ScriptDir%\snippet\address\address.ahk
#include %A_ScriptDir%\snippet\shell.ahk
#include %A_ScriptDir%\temp.ahk
#include %A_ScriptDir%\test.ahk
