#include %A_ScriptDir%\controller\application-vscode.ahk
#include %A_ScriptDir%\controller\application.ahk
#include %A_ScriptDir%\controller\everything.ahk
#include %A_ScriptDir%\controller\global-mouse-cursor.ahk
#include %A_ScriptDir%\controller\global.ahk
#include %A_ScriptDir%\controller\terminal.ahk
#include %A_ScriptDir%\controller\vscode.ahk
#include %A_ScriptDir%\controller\web.ahk
#include %A_ScriptDir%\controller\windows.ahk
#include %A_ScriptDir%\controller\wps.ahk
#include %A_ScriptDir%\controller\wsl.ahk
#include %A_ScriptDir%\function\activeApplication.ahk
#include %A_ScriptDir%\function\function.ahk
#include %A_ScriptDir%\function\IME.ahk
#include %A_ScriptDir%\function\send.ahk
#include %A_ScriptDir%\myhotkey.ahk
#include %A_ScriptDir%\shortcut\git.ahk
#include %A_ScriptDir%\shortcut\linux\linux-fzf.ahk
#include %A_ScriptDir%\shortcut\linux\linux.ahk
#include %A_ScriptDir%\shortcut\openbmc.ahk
#include %A_ScriptDir%\shortcut\regex\regex.ahk
#include %A_ScriptDir%\shortcut\route\route-ip.ahk
#include %A_ScriptDir%\shortcut\route\route-openbmc-2600.ahk
#include %A_ScriptDir%\shortcut\route\route-openbmc-romlus.ahk
#include %A_ScriptDir%\shortcut\route\route-openbmc.ahk
#include %A_ScriptDir%\shortcut\route\route-wsl.ahk
#include %A_ScriptDir%\shortcut\route\route.ahk
#include %A_ScriptDir%\shortcut\search.ahk
#include %A_ScriptDir%\shortcut\shell.ahk
#include %A_ScriptDir%\snippet\address\address.ahk
#include %A_ScriptDir%\snippet\snippet.ahk
#include %A_ScriptDir%\snippet\time\time.ahk
#include %A_ScriptDir%\temp.ahk
#include %A_ScriptDir%\test.ahk
