#include %A_ScriptDir%\myhotkey.ahk
#include %A_ScriptDir%\src\controller\application-vscode.ahk
#include %A_ScriptDir%\src\controller\application.ahk
#include %A_ScriptDir%\src\controller\chrome.ahk
#include %A_ScriptDir%\src\controller\edge.ahk
#include %A_ScriptDir%\src\controller\everything.ahk
#include %A_ScriptDir%\src\controller\global-mouse-cursor.ahk
#include %A_ScriptDir%\src\controller\global.ahk
#include %A_ScriptDir%\src\controller\linux-fzf.ahk
#include %A_ScriptDir%\src\controller\terminal.ahk
#include %A_ScriptDir%\src\controller\time.ahk
#include %A_ScriptDir%\src\controller\vscode.ahk
#include %A_ScriptDir%\src\controller\web.ahk
#include %A_ScriptDir%\src\controller\windows.ahk
#include %A_ScriptDir%\src\controller\wps.ahk
#include %A_ScriptDir%\src\controller\wsl.ahk
#include %A_ScriptDir%\src\function\activeApplication.ahk
#include %A_ScriptDir%\src\function\function.ahk
#include %A_ScriptDir%\src\function\IME.ahk
#include %A_ScriptDir%\src\function\send.ahk
#include %A_ScriptDir%\src\route\route-ip.ahk
#include %A_ScriptDir%\src\route\route-openbmc-2600.ahk
#include %A_ScriptDir%\src\route\route-openbmc-romlus.ahk
#include %A_ScriptDir%\src\route\route-openbmc.ahk
#include %A_ScriptDir%\src\route\route.ahk
#include %A_ScriptDir%\src\shortcut\output.ahk
#include %A_ScriptDir%\src\snippet\snippet.ahk
