:*:ga,::
sendFile("\snippet\src\address\ga-gitaddress.txt")
return
:*:ma,::
sendFile("\snippet\src\address\ma-musicaddress.txt")
return
:*:cp,::
sendFile("\snippet\src\c\cp-print.c")
return
:*:lk,::
sendFile("\snippet\src\markdown\lk-link.txt")
return
:*:fg,::
sendFile("\snippet\src\shell\fg-findgshell.sh")
return
