;windows的wsl的快捷键
:*:wgao,::/mnt/d/Users/gao/
:*:ws,::/mnt/d/share/
:*:wwd,::/mnt/d/share/docs/workdoc/
:*:wsw,::/mnt/d/share/docs/siwei/
:*:wsh,::/mnt/d/share/shenghuo/
:*:wd,::/mnt/d/share/docs/
:*:wg,::/mnt/d/share/gshell/
:*:ww,::/mnt/d/share/work/
:*:wbai,::/mnt/f/BaiduNetdiskDownload/
:*:wgiao,::/mnt/d/share/giaoAutohotkey/
