:*:b,::bash ~/work_mount/gshell/

;change_apt_mirror18.sh
;change_apt_mirror20.sh
;change_name.sh
;git_config_gitee.sh
;git_config.sh
;git_new.sh

git_openbmc_branch.sh
git_pull_all.sh
git_push_all.sh
git_push.sh
hello.sh
install_bitbake.sh
install_git_commit_template.sh
install_IAR.sh
install_necessary_apt.sh
install_nfs.sh 
install_nvim.sh
install_openBMC_qemu.sh
install_openBMC.sh
install_rigpre.sh
install_static_ip_for_home.sh
install_static_ip_for_work131.sh
install_sys_ubuntu18.sh
install_sys_ubuntu20.sh
install_tftp.sh
install_vim81.sh
install_vim_plug.sh
install_youcompleteme.sh
lsx_client.sh
modify_openBMC_config.sh
openbmc_change_dhcp.sh
openbmc_change_static.sh
prepare_vim.sh
run_openBMCi_by_port127.sh
run_openBMCi_by_port_home131_post.sh
run_openBMCi_by_port_home131.sh
run_openBMCi_by_port_work131_post.sh
run_openBMCi_by_port_work131.sh
run_when_reload.sh
scp_openbmc_serve.sh
scp_openbmc_test.sh
source_bitbake.sh
source_install_bashrc.sh
stop_openBMC.sh
system_plat.sh
test.txt
translate.js
vmware_run.sh