:*:ga,::
sendFile("\src\snippet\src\address\ga-gitaddress.txt")
return
:*:ma,::
sendFile("\src\snippet\src\address\ma-musicaddress.txt")
return
:*:cp,::
sendFile("\src\snippet\src\c\cp-print.c")
return
:*:lk,::
sendFile("\src\snippet\src\markdown\lk-link.txt")
return
:*:fc,::
sendFile("\src\snippet\src\shell\fc-filecontent.sh")
return
:*:fd,::
sendFile("\src\snippet\src\shell\fd-findaddr.sh")
return
:*:fg,::
sendFile("\src\snippet\src\shell\fg-findgshell.sh")
return
