:*:bbmc,::
sendByClipboard("bitbake obmc-phosphor-image")
return
:*:bmc,::
sendByClipboard("obmc-phosphor-image")
return
:*:ebmcp,::
sendByClipboard("export TEMPLATECONF=meta-ibm/meta-palmetto/conf  && . openbmc-env")
return
:*:gita,::
sendByClipboard("git add . && git commit --no-verify && git push --set-upstream")
return
:*:fd,::
sendByClipboard("$FD")
return
:*:vm,::
sendByClipboard("sudo /sbin/mount.vboxsf work_mount ~/work_mount/")
return
:*:wmnd,::
sendByClipboard("/mnt/d/share/data/docs/myNavigation/doc-")
return
:*:es,::
sendByClipboard("D:\share\")
return
:*:efbai,::
sendByClipboard("F:\BaiduNetdiskDownload\")
return
:*:eebai,::
sendByClipboard("E:\BaiduNetdiskDownload\")
return
:*:eg,::
sendByClipboard("D:\share\gshell\src\")
return
:*:egiao,::
sendByClipboard("D:\share\giaoAutohotkey\")
return
:*:ep,::
sendByClipboard("D:\share\data\project\")
return
:*:epic,::
sendByClipboard("D:\share\data\picmind\")
return
:*:ed,::
sendByClipboard("D:\share\data\docs\")
return
:*:esw,::
sendByClipboard("D:\share\data\docs\siwei")
return
:*:ead,::
sendByClipboard("D:\share\data\docs\adoc")
return
:*:exm,::
sendByClipboard("D:\share\data\docs\adoc\fangfa-xiangmu")
return
:*:egh,::
sendByClipboard("D:\share\data\docs\adoc\aim-")
return
:*:emn,::
sendByClipboard("D:\share\data\docs\myNavigation\")
return
:*:et,::
sendByClipboard("D:\share\data\docs\trash\")
return
:*:ww,::
sendByClipboard("/mnt/d/share/work/")
return
:*:wwt,::
sendByClipboard("/mnt/d/share/data/docs/worktemp")
return
:*:ws,::
sendByClipboard("/mnt/d/share/")
return
:*:wwp,::
sendByClipboard("/mnt/d/share/work/post/")
return
:*:fbai,::
sendByClipboard("/mnt/f/BaiduNetdiskDownload/")
return
:*:ebai,::
sendByClipboard("/mnt/e/BaiduNetdiskDownload/")
return
:*:wg,::
sendByClipboard("/mnt/d/share/gshell/src/")
return
:*:wgiao,::
sendByClipboard("/mnt/d/share/giaoAutohotkey/")
return
:*:wpdf,::
sendByClipboard("/mnt/d/share/data/big/book/")
return
:*:wp,::
sendByClipboard("/mnt/d/share/data/project/")
return
:*:wpic,::
sendByClipboard("/mnt/d/share/data/picmind/")
return
:*:wd,::
sendByClipboard("/mnt/d/share/data/docs/")
return
:*:wt,::
sendByClipboard("/mnt/d/share/data/docs/trash/")
return
:*:wwd,::
sendByClipboard("/mnt/d/share/data/docs/workcache")
return
:*:wsw,::
sendByClipboard("/mnt/d/share/data/docs/siwei")
return
:*:wad,::
sendByClipboard("/mnt/d/share/data/docs/adoc/")
return
:*:wxm,::
sendByClipboard("/mnt/d/share/data/docs/adoc/fangfa-xiangmu")
return
:*:wgh,::
sendByClipboard("/mnt/d/share/data/docs/adoc/aim-")
return
:*:gjs,::
sendByClipboard("/mnt/d/share/data/docs/adoc/aim-jishu")
return
:*:grs,::
sendByClipboard("/mnt/d/share/data/docs/adoc/aim-rensheng")
return
:*:wsc,::
sendByClipboard("/mnt/d/share/data/docs/adoc/shengchan")
return
:*:wr,::
sendByClipboard("/mnt/d/share/data/docs/adoc/yuanli-ren")
return
:*:wjc,::
sendByClipboard("/mnt/d/share/data/docs/adoc/wodejuece")
return
:*:wxx,::
sendByClipboard("/mnt/d/share/data/docs/adoc/fangfa-xuexi-")
return
:*:wxf,::
sendByClipboard("/mnt/d/share/data/docs/adoc/xiangfa-")
return
:*:wzl,::
sendByClipboard("/mnt/d/share/data/docs/adoc/fangfa-zhengli-")
return
:*:wmn,::
sendByClipboard("/mnt/d/share/data/docs/myNavigation/")
return
:*:nd,::
sendByClipboard("/mnt/d/share/data/docs/myNavigation/doc-")
return
:*:np,::
sendByClipboard("/mnt/d/share/data/docs/myNavigation/proj")
return
:*:nn,::
sendByClipboard("/mnt/d/share/data/docs/myNavigation/daohang")
return
:*:bxjb,::
sendByClipboard("编写脚本")
return
:*:kw,::
sendByClipboard("功能,为了,目的,区别,总结,组成,流程,例如,举例,示例,为例,例子,比如,包括,包含,属性,定义,概念,介绍,称为,对象,宏定义,关键字,函数,文件,配置,方案,问题,表示,模型,不同,差别,相比,使用,原理,步骤,下图,属于,实现,同理,但是,阶段,模式,ifdef,类型,是指,优点,缺点,规则")
return
:*:kwk,::
sendByClipboard("功能 为了 目的 区别 总结 组成 流程 例如 举例 示例 为例 例子 比如 包括 包含 属性 定义 概念 介绍 称为 对象 宏定义 关键字 函数 文件 配置 方案 问题 表示 模型 不同 差别 相比 使用 原理 步骤 下图 属于 实现 同理 但是 阶段 模式 ifdef 类型 是指 优点 缺点 规则")
return
:*:ekw,::
sendByClipboard("function,aim,difference,sum,compos,example,sample,instance,define,concept,that,as,by,or,and,for")
return
