:*:bbmc,::
sendByClipboard("bitbake obmc-phosphor-image")
return
:*:bmc,::
sendByClipboard("obmc-phosphor-image")
return
:*:ebmcp,::
sendByClipboard("export TEMPLATECONF=meta-ibm/meta-palmetto/conf  && . openbmc-env")
return
:*:gita,::
sendByClipboard("git add . && git commit --no-verify && git push --set-upstream")
return
:*:fd,::
sendByClipboard("$FD")
return
:*:pg,::
sendByClipboard("$pg")
return
:*:vm,::
sendByClipboard("sudo /sbin/mount.vboxsf work_mount ~/work_mount/")
return
:*:wmnd,::
sendByClipboard("/mnt/d/share/data/docs/myNavigation/doc-")
return
:*:ps,::
sendByClipboard("D:\share\")
return
:*:pfbai,::
sendByClipboard("F:\BaiduNetdiskDownload\")
return
:*:pebai,::
sendByClipboard("E:\BaiduNetdiskDownload\")
return
:*:pg,::
sendByClipboard("D:\share\gshell\src\")
return
:*:pgiao,::
sendByClipboard("D:\share\giaoAutohotkey\")
return
:*:pp,::
sendByClipboard("D:\share\data\project\")
return
:*:ppic,::
sendByClipboard("D:\share\data\picmind\")
return
:*:pd,::
sendByClipboard("D:\share\data\docs\")
return
:*:psw,::
sendByClipboard("D:\share\data\docs\siwei")
return
:*:pad,::
sendByClipboard("D:\share\data\docs\adoc")
return
:*:pxm,::
sendByClipboard("D:\share\data\docs\adoc\fangfa-xiangmu")
return
:*:pgh,::
sendByClipboard("D:\share\data\docs\adoc\aim-")
return
:*:pmn,::
sendByClipboard("D:\share\data\docs\myNavigation\")
return
:*:pt,::
sendByClipboard("D:\share\data\docs\trash\")
return
:*:bxjb,::
sendByClipboard("编写脚本")
return
